# Generated by Django 3.1.2 on 2022-10-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='ph_number',
            field=models.CharField(default='1234567890', max_length=20),
        ),
    ]
